### ISSUE TITLE
отображение действий для точки

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#11]
При просмотре точки отображать кнопки:
- пролистывание (можно не кнопки, а иконки по краям экрана)
- редактирование (если можно редактировать, то активная кнопка, если нельзя, то пассивная) открывать форму добавления точки с заполненными полями, выполнять запрос на добавление
- публикация (если у пользователя есть права на публикацию (userinfo -> isTrustedUser=true), то отображать кнопку. 2 режима: опубликовать, отменить публикацию).

**Comment by ksarkes** [comment]
Реализовано кроме пролистывания, перенесено #17
