### ISSUE TITLE
управление публикацией и фильтрацией точек

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#19]
В верхней панели главной формы сделать кнопку отображения списка категорий.
В списке категорий для каждой записи должно быть:
- иконка категории
- чекбокс фильтрации отображаемых на карте категорий (по умолчанию все категории отображаются)
- название категории
- одна кнопка публикации/отмены публикации категории

Кнопка отображается при наличии прав у пользователя. Действие кнопки определяется по наличию и значению поля published категории

**Comment by ksarkes** [comment]
https://github.com/oss-fruct-org/gets-supplement-android/commit/a1aef2d92f1f7b85942739e4780b3f54b82b22e2 https://github.com/oss-fruct-org/gets-supplement-android/commit/94c9cc1b971201e281501e52548bff17117b003f https://github.com/oss-fruct-org/gets-supplement-android/commit/6608e8c7da3338a2bc52c11b74991a9bdefee83e
