### ISSUE TITLE
незагрузка некоторых видов препятствий

### ISSUE THREAD

**Issue by petrsudevel** [oss-fruct-org/gets-supplement-android#24]
ставил препятствия в кондопоге на сервер загрузились только лестницы и пешеходные переходы

**Comment by ksarkes** [comment]
какой toast выдавало при добавлении?

**Comment by petrsudevel** [comment]
в петрозаводске тоже не добавляются точнее добавляются только лестницы (тестировал лестницы, уклон и узкую дорогу)

**Comment by temansky** [comment]
протетестил на 2-х гугл аккаунтах и 3 устройствах, подобной проблемы не обнаружено (тестил GeTS Supplement), а точки в нем не грузятся или в навигаторе?

**Comment by petrsudevel** [comment]
точки не грузятся нигде кроме устройства с которого залиты в веб версии их тоже не появляется

**Comment by ksarkes** [comment]
Категории, точки которых добавляются, опубликованы на устройстве?

**Comment by petrsudevel** [comment]
вроде да покрайней мере я нажимал на кнопку их добавления в опубликованных категориях

**Comment by ksarkes** [comment]
нажми на все еще раз и пробуй добавлять

**Comment by petrsudevel** [comment]
добавил на стадионе в ямке петргу уклон и узкую дорогу на устройстве они есть и была надпись что отправленны на сервер, в веб версии их нет
