### ISSUE TITLE
Функция магнита при установке точек

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#30]
1. реализовать загрузку графа дорог аналогично навигатору
2. при добавлении точки притягивать маркер к ближайшей дороге графа (нормаль на ребро графа).
3. отображать название улицы к которой притянут маркер
4. при добавлении точки добавлять свойство streetid с идентификатором улицы
5. добавить возможность отключить магнит в настройках приложения

**Comment by ksarkes** [comment]
https://github.com/oss-fruct-org/gets-supplement-android/commit/0c5e8cc531be351018fd4069cea0930332e2ceaa

**Comment by ksarkes** [comment]
id улицы передается в <extended_data><street_id>id</street_id></extended_data>
