### ISSUE TITLE
Умное обновление графа дорог

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#31]
При запуске приложения загружать XML со списком графов при наличии сети. Адрес точки загрузки указать в конфиге. Если XML загрузилось успешно, то проверять дату обновления текущего региона (если геолокация не включена, то выдать окно с предложением включить геолокацию). Если в XML есть обновление (или на устройстве нет загруженного региона), выдавать окно с предложением загрузить обновление графа дорог. Если пользователь соглашается, то выполнить загрузку. Если загрузка успешна, то заменить текущий граф на новый. Если загрузка неуспешна, то сообщить о проблеме и вернуться к окну с предложением о загрузке обновления. Если пользователь отказывается загружать обновление, то использовать старый граф с магнитом. Если нет старого графа, то магнит отключить.

**Comment by ksarkes** [comment]
https://github.com/oss-fruct-org/gets-supplement-android/commit/0080fdacea3a12b6eb14312e3fb5e9cd7df4cd5b
