### ISSUE TITLE
отслеживать включение/отключение геопозиционирования

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#4]
Приложение должно отслеживать включение/отключение геопозиционирования.

При включении: запуск отслеживания местоположения пользователя
При выключении: остановка отслеживания отображение точек для последних координат
При запуске приложения: определение статуса геопозиционирования, отработка статуса

**Comment by seekerk** [comment]
В версии 10 при переключении режимов геопозиционирования отображается местоположение, но не работает кнопка перехода в текущее местоположение (отображается вся карта)

**Comment by temansky** [comment]
https://github.com/oss-fruct-org/gets-supplement-android/commit/384dcb95ebc870c13ecb6b2a41e3916d9fa2d4c3
